export default [
  // Ignore folders
  {
    ignores: [
      'node_modules/**',
      'dist/**',
      'build/**',
      'coverage/**',
      'playwright-report/**',
      '.git/**',
      'Docs/**',
    ],
  },
  // Main JS files
  {
    files: ['**/*.js', '**/*.mjs'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        // Browser globals
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        fetch: 'readonly',
        Audio: 'readonly',
        DOMParser: 'readonly',
        requestAnimationFrame: 'readonly',
        performance: 'readonly',
        Image: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        URL: 'readonly',
        location: 'readonly',
        confirm: 'readonly',
        history: 'readonly',
        DocumentTouch: 'readonly',
        NodeList: 'readonly',
        getComputedStyle: 'readonly',
        navigator: 'readonly',
        CustomEvent: 'readonly',
        prompt: 'readonly',
        // Library/module globals
        define: 'readonly',
        module: 'readonly',
        PR: 'readonly',
        Split: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': 'warn',
      'no-undef': 'error',
    },
  },
  // Service Worker
  {
    files: ['service-worker.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        self: 'readonly',
        caches: 'readonly',
        clients: 'readonly',
        console: 'readonly',
        fetch: 'readonly',
        Promise: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': 'warn',
      'no-undef': 'error',
    },
  },
  // Test files
  {
    files: ['**/*.test.js', '**/*.spec.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        // Browser globals
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        fetch: 'readonly',
        Audio: 'readonly',
        DOMParser: 'readonly',
        requestAnimationFrame: 'readonly',
        performance: 'readonly',
        Image: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        URL: 'readonly',
        location: 'readonly',
        confirm: 'readonly',
        history: 'readonly',
        DocumentTouch: 'readonly',
        NodeList: 'readonly',
        getComputedStyle: 'readonly',
        navigator: 'readonly',
        // Library/module globals
        define: 'readonly',
        module: 'readonly',
        PR: 'readonly',
        Split: 'readonly',
        // Vitest/testing globals
        beforeAll: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        afterAll: 'readonly',
        describe: 'readonly',
        it: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        vi: 'readonly',
        global: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': 'warn',
      'no-undef': 'error',
    },
  },
  // Node + config + tests
  {
    files: ['playwright.config.js', 'vitest.config.js', 'tests/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        // Node.js globals
        process: 'readonly',
        console: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        global: 'readonly',
        // Browser globals
        window: 'readonly',
        document: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        fetch: 'readonly',
        Audio: 'readonly',
        DOMParser: 'readonly',
        requestAnimationFrame: 'readonly',
        performance: 'readonly',
        Image: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        URL: 'readonly',
        location: 'readonly',
        confirm: 'readonly',
        history: 'readonly',
        DocumentTouch: 'readonly',
        NodeList: 'readonly',
        getComputedStyle: 'readonly',
        navigator: 'readonly',
        // Library/module globals
        define: 'readonly',
        module: 'readonly',
        PR: 'readonly',
        Split: 'readonly',
        // Vitest/testing globals
        beforeAll: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        afterAll: 'readonly',
        describe: 'readonly',
        it: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        vi: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': 'warn',
      'no-undef': 'error',
    },
  },
];
